[[main]]
url = "/"
name = "Home"
weight = 1

[[main]]
url = "/posts/"
name = "Posts"
weight = 2

[[icon]]
    url = "https://www.youtube.com/channel/UCVYje6c5eOPJwu2-1tfQiEw"
    name = "youtube"
    weight = 1

[[icon]]
    url = "https://www.linkedin.com/in/hankli0130"
    name = "linkedin"
    weight = 2

[[icon]]
    url = "https://github.com/HankLi0130/"
    name = "github"
    weight = 3

[[icon]]
    url = "mailto:hankli0130@gmail.com"
    name = "envelope-o"
    weight = 4