[[main]]
url = "/"
name = "Home"
weight = 1

[[main]]
url = "/posts"
name = "Posts"
weight = 2

[[icon]]
    url = "https://www.youtube.com/channel/UCVYje6c5eOPJwu2-1tfQiEw"
    name = "fab fa-youtube"
    weight = 1  

[[icon]]
    url = "https://github.com/HankLi0130"
    name = "fab fa-github"
    weight = 2

[[icon]]
    url = "mailto:hankli0130@gmail.com"
    name = "fas fa-envelope"
    weight = 3