author = "Hank Li"
description = "I am from Taiwan 🇹🇼."
githubUsername = "HankLi0130"
accent = "#007bff"
showBorder = false
backgroundColor = "white"
font = "Roboto" # should match the name on Google Fonts!
highlight = true
highlightStyle = "default"
highlightLanguages = ["kotlin", "swift"]

profilePic = "/profile/hank_avatar.png"
copyright = "Copyright © 2021 ~ 2024 Hank Li. All rights reserved."
