author = "Hank Li"
description = "Shares Android development and Kotlin programming."
githubUsername = "HankLi0130"
accent = "#E4CD05"
showBorder = true
backgroundColor = "white"
font = "RalReway" # should match the name on Google Fonts!
highlight = true
highlightStyle = "default"
highlightLanguages = ["kotlin"]

profilePic = "/profile/hank_head_shot.jpg"
copyright = "Copyright © 2021 Hank Dev. All rights reserved."
